### ISSUE TITLE
Some warnings when running installation

### ISSUE THREAD

**Issue by zg** [underscoreio/creative-scala#2]
$ npm install
npm WARN package.json eescala@1.0.0 No repository field.
npm WARN engine bootstrap@3.3.2: wanted: {"node":"~0.10.1"} (current: {"node":"0.12.0","npm":"2.5.1"})

**Comment by noelwelsh** [comment]
I've fixed the one error we can fix (no repository field). The other is an upstream issue. Thanks for the report.
