### ISSUE TITLE
Using coursier for faster artefact resolution

### ISSUE THREAD

**Issue by javierarrieta** [underscoreio/creative-scala#34]
I was wondering if you think that using [cousier](https://github.com/coursier/coursier) for faster artefact resolution could be helpful,  I have tested a branch and it is working. Since the docker is usually a cold resolution cache, this can help a lot (pity it does not work for the sbt and plugin artefacts)

Happy to create a PR from that branch (it is a one-liner anyway)

Thanks for all the hard work!

**Comment by noelwelsh** [comment]
It might be better to add this to the ebook template, so all projects benefit: https://github.com/underscoreio/underscore-ebook-template

**Comment by javierarrieta** [comment]
Sure, I will open it there and submit a pr

But would that apply automagically to all books, is it not necessary to apply it to all repos? (Sorry, not sure if the template is for creation or changes to it are applied to all books)

**Comment by noelwelsh** [comment]
Unfortunately it will then be necessary to manually apply the changes to all the books.

**Comment by davegurnell** [comment]
@noelwelsh The ebook template doesn't touch SBT I think. We added Tut
builds later. This is the right place to add Coursier.

**Comment by javierarrieta** [comment]
created #36 for this, not sure if it would improve things too much. If you think it is positive I will create PR for the other books

**Comment by javierarrieta** [comment]
Btw, tried to bump sbt to `0.13.15` but the project folder is ignored by git, find it very confusing as the `plugins.sbt` lies there

**Comment by davegurnell** [comment]
That's probably historical. Our books weren't originally built with Tut.
It'll be fine to tweak the .gitignore to allow plugins.sbt and
build.properties into Git.

**Comment by javierarrieta** [comment]
Ok, so bumped sbt to 0.13.15 and removed the project folder from .gitignore. Everything is in the PR

I can split in 2 PR's if you prefer, thought those were small changes

**Comment by javierarrieta** [comment]
Tell me if you want me to do this for all the opensource books, happy to help @noelhwelsh @davegurnell

**Comment by noelwelsh** [comment]
If you have time that would be fantastic!

**Comment by javierarrieta** [comment]
I created a few pr bumping sbt and adding coursier, hope that helps. Will take a look at the issues when/if ( 😞 ) I have some spare time

**Comment by SethTisue** [comment]
#36 was merged; should this ticket be closed?

**Comment by noelwelsh** [comment]
👍
