### ISSUE TITLE
Recommend AdoptOpenJDK OpenJDK 8 + HotSpot

### ISSUE THREAD

**Issue by eed3si9n** [underscoreio/creative-scala#58]
Given the complicated license and update situation  (https://www.aspera.com/en/blog/oracle-will-charge-for-java-starting-in-2019/, https://www.oracle.com/technetwork/java/java-se-support-roadmap.html) and ever changing JDKs and Scala's varying degree of support for it, I think Creative Scala should instruct new users explicitly to use Java 8. If someone has an Oracle JDK already that's ok, but for new installs I recommend [AdoptOpenJDK](https://adoptopenjdk.net/) OpenJDK 8 + HotSpot.

It's a binary distribution created from OpenJDK project source. Hopefully it should provide patches long after January, 2019.

**Comment by noelwelsh** [comment]
I installed AdoptOpenJDK on my son's laptop last weekend and discovered that on OS X a library needed for rendering has the wrong name. [Here's one relevant bug](https://github.com/AdoptOpenJDK/openjdk-build/issues/202) (there are a few others that all relate to similar issues.) It's a fairly simple matter to fix (just rename the library) but not something that I would expect Creative Scala's target audience to be comfortable doing.

I agree in principle with this change but I want to wait for AdoptOpenJDK to sort out their packaging. An alternative would be to suggest [Corretto](https://aws.amazon.com/corretto/faqs/), which I believe has fixed this issue already.

**Comment by noelwelsh** [comment]
This is all sorted out now.
