### ISSUE TITLE
Setup / Getting Started Process is Unclear

### ISSUE THREAD

**Issue by noelwelsh** [underscoreio/creative-scala#6]
Creative Scala doesn't do a very good job explaining the setup process for people who are not already fairly proficient programmers:
- get the JVM, if you don't have it already
- get a text editor
- get Doodle
- run sbt

Include how to open the command line on Windows etc.

**Comment by jonoabroad** [comment]
Also describing what the sbt output is.

**Comment by noelwelsh** [comment]
I think what we have is sufficient for now. Duplicate of #14 and closed by a74bd10d4cdd94c7ef289c8a4da96c518b36e51f
