### ISSUE TITLE
Could Not Find Implicit Error when Starting Project

### ISSUE THREAD

**Issue by mattfowler** [underscoreio/creative-scala#69]
Following the instructions the first step run from the sbt console is

`Example.image.draw`

However with the latest version this triggers the following error:

`<console>:27: error: could not find implicit value for parameter renderer: doodle.effect.DefaultRenderer[[x[_]]doodle.language.Basic[x],Nothing,Nothing,Nothing] Example.image.draw`

However, using parens when calling draw properly resolves the implicit and draws the doodle

`Example.image.draw()`

**Comment by noelwelsh** [comment]
👍 Fixed.
